name: flash_chat
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  cloud_firestore: ^3.1.17
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  modal_progress_hud_nsn: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_name: "^0.0.1"

flutter_launcher_name:
  name: "Flash Chat"


flutter:
  uses-material-design: true

  assets:
  - images/
